name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para o branch principal do seu projeto

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Fazer checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Passo 2: Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use a versão do Node.js que seu projeto requer
        cache: 'npm'

    # Passo 3: Instalar dependências
    - name: Install dependencies
      run: npm install

    # Passo 4: Construir o aplicativo
    - name: Build Vite App
      run: npm run build

    # Passo 5: Implantar no GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Diretório padrão onde o Vite coloca os arquivos de produção
